### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by Lycheewe** [shady2k/logseq-inbox-telegram-plugin#1]
sir how to use this? added a telegram bot but nothing happened

**Comment by shady2k** [comment]
After you paste bot token you need to restart plugin.

**Comment by Lycheewe** [comment]
Should I just create a bot and invite it in my telegram group?

**Comment by shady2k** [comment]
Firstly, create a bot with BotFather, which is essentially a bot used to create other bots. The command you need is /newbot. After you choose title, BotFaher give you the token. Paste it into plugin settings and restart plugin.
After that just open chat with your bot and type /start command. Then write any message, it will be added to your Logseq daily journal within 60 seconds. Hope it helps.

**Comment by Lycheewe** [comment]
It works, that's so cool man, good job!

**Comment by Lycheewe** [comment]
And one more question, could I set more than one bot? If so, what should I set in the configuration file?

**Comment by shady2k** [comment]
Describe your use case, please.

**Comment by Lycheewe** [comment]
For example, I want a bot as my #inbox to collect some articles and resources. And I want to create a bot to collect my random thoughts as #spark. That's my use cases.

**Comment by shady2k** [comment]
Now it's not possible, but I will think about it.

**Comment by shady2k** [comment]
@Lycheewe, please check latest release.
