### ISSUE TITLE
authorizedUsers doesn't work

### ISSUE THREAD

**Issue by asuragan** [shady2k/logseq-inbox-telegram-plugin#12]
Не работает authorizedUsers
Не нашел в коде js файла чтобы где-то указывалось logseq.settings.authorizedUsers, хотя все остальные там указываются.

- Указал в настройках authorizedUsers юзернейм
![photo_2022-01-27_21-25-20](https://user-images.githubusercontent.com/55428472/151420922-2c81dfd3-89a9-44da-9024-c1ab81b31b05.jpg)
- Так выглядел дневник изначально
![photo_2022-01-27_21-25-22](https://user-images.githubusercontent.com/55428472/151421570-4e779c71-53df-4e8f-8c7a-abfb6d1da12a.jpg)
- Пишу боту с аккаунта указанного в authorizedUsers и получаю от него такой ответ:
![image_2022-01-27_21-16-38](https://user-images.githubusercontent.com/55428472/151421792-8abd5af6-428e-496c-b554-79b0a31be9ff.png)
- Текст добавляется в дневник:
![photo_2022-01-27_21-25-25](https://user-images.githubusercontent.com/55428472/151422029-e80b6c76-468c-45a9-87aa-ec6639fd5716.jpg)
- Пишу боту с другого аккаунта и получаю от него такой ответ:
![image_2022-01-27_21-19-16](https://user-images.githubusercontent.com/55428472/151422259-e2b73645-8df9-43a5-8d3d-e406a1abbe8d.png)
- Как видно, юзернейм у него другой, но текст все равно добавляется:
![photo_2022-01-27_21-25-28](https://user-images.githubusercontent.com/55428472/151422952-134a0974-d010-4108-b1da-52b48973533d.jpg)

Еще, не знаю, стоит ли это где-то указывать или нет, но есть такой момент, что синхронизация с телегой работает только когда приложение запущено (что в принципе логично :smile: но кто-то, возможно, может подумать, что синхронизация работает и если приложение выключено) 
а также, что ответ бота хранится на сервере только [где-то 24 часа](https://core.telegram.org/bots/api#:~:text=There%20are%20two%20mutually%20exclusive,kept%20longer%20than%2024%20hours.) и если не заходить в приложение больше 24 часов, то сообщение отправленное в телегу не добавится в logseq

**Comment by shady2k** [comment]
Да я еще не выпустил релиз с authorizedUsers, некогда было.
По остальному - спасибо, напишу в readme.

**Comment by shady2k** [comment]
Please, check latest release, `authorizedUsers` were added in version 0.0.4.
