### ISSUE TITLE
Does not work if journal page has not been created in Logseq

### ISSUE THREAD

**Issue by ashishbhateja** [shady2k/logseq-inbox-telegram-plugin#13]
Thanks so much for a great and useful plugin!

I wanted to share the following feedback, and in case this can be fixed in the upcoming releases:
I tried to make an early morning entry via telegram before I had opened my loges app. Later, when I opened the app, I got an error message on the app saying journal entry not found by the plugin.

**Comment by shady2k** [comment]
What plugin version do you have? I had added delay before search for today page.

**Comment by ashishbhateja** [comment]
It's the current version. Here's a screenshot of the error message

<img width="379" alt="image" src="https://user-images.githubusercontent.com/69289857/151728472-e9ad9a6c-9316-4a3f-a54e-cb5c63e70297.png">

**Comment by shady2k** [comment]
If this issue still reproducing, than let's do some things:
- open your today's journal page by clicking on date
- go to three dots on top right corner of app
- choose (Dev) Show page data
- paste here this information

**Comment by ashishbhateja** [comment]
Thanks for 

> If this issue still reproducing, than let's do some things:
> 
> * open your today's journal page by clicking on date
> * go to three dots on top right corner of app
> * choose (Dev) Show page data
> * paste here this information

**Comment by ashishbhateja** [comment]
Thanks. There was an issue with my Logseq data because of which the database was super slow. I was able to reconstruct it with improvements in speed. Now the plugin seems to work as it should.
