### ISSUE TITLE
cannot open the setting page

### ISSUE THREAD

**Issue by lyh910** [shady2k/logseq-inbox-telegram-plugin#16]
**Desktop Platform Information**
Windows 10, logseq 0.6.3

after installing this plugin, there was nothing happened when I clicked the 'open setting' button on the plugin page. In addition, this plugin didn't appear in the 'settings of plugins' section in Setting either. Other plugins like 'Random Note' works well, however.

Reinstallation or switching to manual installation doesn't help. I wonder if I did something wrong.

**Comment by shady2k** [comment]
Duplicate https://github.com/shady2k/logseq-inbox-telegram-plugin/issues/23
