### ISSUE TITLE
Not Receiving Messages from Bots Sent to a Group

### ISSUE THREAD

**Issue by harshadwaj** [shady2k/logseq-inbox-telegram-plugin#20]
Messages from users comes fine but not from those sent from bots.

Example usage - I have setup an iOS shortcut to send message to a telegram group using the api. Those are not delivered to Logseq even though I can see them appear in the group.

Also, the "authorizesUsers":[] is empty to allow message from all users.

**Comment by shady2k** [comment]
Hello! And how does this iOS shortcut send messages? From which user do they sent? Can you post here its code? Or, maybe, you could create test group with this messages and invite me @shady2k to this group and I've inspect this messages.

**Comment by harshadwaj** [comment]
I created iOS shortcut to send message to a telegram group instead of opening the app. The shortcut uses the telegram POST API.
The format is: `https://api.telegram.org/bot<bot-token>/sendMessage` as url and body containing two form fields - `chat_id` and `text`.

The token used is of the bot and it appears ok in the group as sent by bot. Logseq does not pull these messages.

**Comment by shady2k** [comment]
You should try:
- Write BotFather /setprivacy command and set it to DISABLED

**Comment by harshadwaj** [comment]
That is the setting that I have already done to make the bot work as per the instructions. Verified again and its DISABLED. Still no messages from bot only. From user works fine.

**Comment by shady2k** [comment]
Ok, let's try:
- Disable plugin
- Send any message via your shortcut
- Execute `https://api.telegram.org/bot${botToken}/getUpdates` in your browser, where `${botToken}` is you bot token
- Send result here

**Comment by harshadwaj** [comment]
I did some more testing and figured out that it is the constraint of the Telegram API and it has nothing to do with your plugin. In summary, [bots cannot read messages from other bots](https://core.telegram.org/bots/faq#why-doesn-39t-my-bot-see-messages-from-other-bots).

However, I am not sure how and why it works in [Telegroam](https://github.com/mbrock/telegroam). Maybe because of the proxy server?

**Comment by shady2k** [comment]
I'm not sure. Probably proxy used for work with files from Telegram. Can you do that I was asked you before?

**Comment by harshadwaj** [comment]
I did and the `getUpdates` does not fetch messages posted through Shortcut (which is using bot). Returns an empty array as `result: [ ]`. The reason for that is the official docs link I have posted.

**Comment by shady2k** [comment]
I have no idea what do with this. I were inspected the code of telegroam, it uses same way to fetch messages from Telegram.

**Comment by harshadwaj** [comment]
I had to refer to my notes to figure out what I had done to make it work. Telegroam also does not handle this by default. I had updated its code. Here is the summary of what I had done, so that you can update your code to make it work:

1. Create two bots - a push bot and pull bot
2. Use pull bot's token to pull (in Telegroam and in future in this plugin) and push bot's token in the iOS Shortcut
3. Create a channel and add both bots as admins.
4. Set privacy DISABLED for both bots and make sure add to groups is set to TRUE.
5. Had changed the code in [this line](https://github.com/mbrock/telegroam/blob/f0cad962dc0385187e6628b2f2873bf2225171f4/telegroam.js#L189) to add `channel_post` to this list. You have to do something similar to process messages from a channel.
6. Send a POST message from iOS Shortcut.
7. Make sure it appears in the channel and through the `getUpdates` API

This worked in Telegroam and also will work in your plugin because the above restriction I mentioned that bots cannot read bots does not apply to channel messages.

**Comment by shady2k** [comment]
Can you check with new version?

**Comment by harshadwaj** [comment]
Works perfect now. Getting messages from channel pushed through Shortcut. A minor annoyance (not related to this) is that messages gets added next to the first block in the journal but not at the end of all the blocks.

Otherwise, its working perfectly fine. Thanks for such a quick update.
