### ISSUE TITLE
Messages gets added next to the first block

### ISSUE THREAD

**Issue by shady2k** [shady2k/logseq-inbox-telegram-plugin#22]
Messages gets added next to the first block in the journal but not at the end of all the blocks.

**Comment by mzwlevi** [comment]
> Messages gets added next to the first block in the journal but not at the end of all the blocks.

This bug was still reproduced in 0.7.5

**Comment by mzwlevi** [comment]
https://user-images.githubusercontent.com/78029539/177125567-68500f70-83e5-4a76-ae37-e36834065a30.mov

**Comment by mzwlevi** [comment]
When I have written something in Logseq, then I use the Telegram to send messages to Logseq, the bug was occurred.
