### ISSUE TITLE
Does not receive anything

### ISSUE THREAD

**Issue by zerone01y** [shady2k/logseq-inbox-telegram-plugin#28]
I followed the readme file and set up the configuration like below:
```
{
  "botToken": "my-token",
  "pollingInterval": 60000,
  "inboxName": "#inbox",
  "authorizedUsers": [],
  "addTimestamp": true,
  "invertMessagesOrder": false,
  "inboxByChat": []
}
```

However, I'm not able to receive anything in logseq journal after sending some text to the bot. I should mention that I once switched between two graphs, but neither of them received any messages from telegram. I noticed that an entries was added to the settings.json, after sending the messages:
```
  "updateId": 88218559
```

I also checked `https://api.telegram.org/bot<token>/getUpdates`, and I saw new messages immediately.

Can you help with the issue? Thanks.

**Comment by shady2k** [comment]
Probably you need to add your username to `authorizedUsers` array.

**Comment by zerone01y** [comment]
An update: I can now receive the messages in Logseq. 

I didn't change the settings but found that I need to restart logseq. (I deactivated the plugin and activated it but it was not effective).
