### ISSUE TITLE
Plugin does not react 

### ISSUE THREAD

**Issue by noadminonly** [shady2k/logseq-inbox-telegram-plugin#31]
Actually, you can't do anything wrong when configuring the plug-in. I entered the bot token, restarted the plugin in logseq (and then logseq itself). Then the bot was started. 
When I send a message now, nothing arrives in logseq. The desktop app is running. Any idea what is going wrong?

**Comment by shady2k** [comment]
Try this:
Write BotFather /setprivacy command and set it to DISABLED

**Comment by noadminonly** [comment]
Hello 
I did this

BotFather, [04.01.23 16:31]
'Enable' - your bot will only receive messages that either start with the '/' symbol or mention the bot by username.
'Disable' - your bot will receive all messages that people send to groups.
Current status is: ENABLED

XXX, [04.01.23 16:32]
Disable

BotFather, [04.01.23 16:32]
Success! The new status is: DISABLED. /help

I restartet logseq and send some telegramm-Messages but nothing happens...

**Comment by saccohuo** [comment]
> Try this: Write BotFather /setprivacy command and set it to DISABLED

Recently it cannot works. I tried this, it don't works either.
logseq version:0.8.15

**Comment by shady2k** [comment]
By default it fetch new messages through 3 seconds after plugin starts and then each minute. Can you post here json settings of your plugin? Don't forget to replace bot token with other text.

**Comment by shady2k** [comment]
No, that's not what I asked for. Go to the plugin settings, and in the top right corner, you will see a link labeled "Edit settings.json". Click on it and you will be able to view the plugin settings. Please paste them here.

**Comment by noadminonly** [comment]
If i do like you describe   I get this entrys 


{
  "botToken": "Her ist my bot token",
  "pollingInterval": 60000,
  "inboxName": "#inbox",
  "authorizedUsers": [],
  "addTimestamp": false,
  "invertMessagesOrder": false,
  "inboxByChat": [],
  "isDebug": false,
  "disabled": false
}

**Comment by shady2k** [comment]
It seems correct. Let's do following steps:
1. Disable plugin
2. Turn on debug mode in plugin settings
3. Press `Ctrl + Shift + I` to open developer console
4. Enable plugin
5. Paste here output from console

**Comment by noadminonly** [comment]
I hope this is helps:

Failed to load resource: net::ERR_NETWORK_CHANGED
api.telegram.org/bot5627263008:AAGBggnb8ARJeisuZsktzOJLQyHELPd_FwE/getUpdates:1          Failed to load resource: net::ERR_NETWORK_CHANGED
api.telegram.org/bot5627263008:AAGBggnb8ARJeisuZsktzOJLQyHELPd_FwE/getUpdates:1          Failed to load resource: net::ERR_NETWORK_CHANGED
api.telegram.org/bot5627263008:AAGBggnb8ARJeisuZsktzOJLQyHELPd_FwE/getUpdates:1          Failed to load resource: net::ERR_NETWORK_CHANGED
api.telegram.org/bot5627263008:AAGBggnb8ARJeisuZsktzOJLQyHELPd_FwE/getUpdates:1          Failed to load resource: net::ERR_NETWORK_CHANGED
api.telegram.org/bot5627263008:AAGBggnb8ARJeisuZsktzOJLQyHELPd_FwE/getUpdates:1          Failed to load resource: net::ERR_NETWORK_CHANGED
api.telegram.org/bot5627263008:AAGBggnb8ARJeisuZsktzOJLQyHELPd_FwE/getUpdates:1          Failed to load resource: net::ERR_NETWORK_CHANGED
api.telegram.org/bot5627263008:AAGBggnb8ARJeisuZsktzOJLQyHELPd_FwE/getUpdates:1          Failed to load resource: net::ERR_NETWORK_CHANGED
api.telegram.org/bot5627263008:AAGBggnb8ARJeisuZsktzOJLQyHELPd_FwE/getUpdates:1          Failed to load resource: net::ERR_NETWORK_CHANGED
api.telegram.org/bot5627263008:AAGBggnb8ARJeisuZsktzOJLQyHELPd_FwE/getUpdates:1          Failed to load resource: net::ERR_NETWORK_CHANGED
api.telegram.org/bot5627263008:AAGBggnb8ARJeisuZsktzOJLQyHELPd_FwE/getUpdates:1          Failed to load resource: net::ERR_NETWORK_CHANGED
api.telegram.org/bot5627263008:AAGBggnb8ARJeisuZsktzOJLQyHELPd_FwE/getUpdates:1          Failed to load resource: net::ERR_NETWORK_CHANGED
index.1ca59d04.js:1 [Inbox Telegram] Started!
index.1ca59d04.js:1 [Inbox Telegram] Polling started!
index.1ca59d04.js:1 Processing
index.1ca59d04.js:1 {messages: Array(0)}
index.1ca59d04.js:1 [Inbox Telegram] Started!
index.1ca59d04.js:1 [Inbox Telegram] Polling started!
index.1ca59d04.js:1 Processing
index.1ca59d04.js:1 {messages: Array(0)}messages: [][[Prototype]]: Object
index.1ca59d04.js:1 Processing
index.1ca59d04.js:1 {messages: Array(0)}messages: Array(0)[[Prototype]]: Object
index.1ca59d04.js:1 Processing
index.1ca59d04.js:1 {messages: Array(0)}
instrument.js:191 D:Search > Transact pages!: logseq_local_/Users/uwe/Library/Mobile Documents/iCloud~com~logseq~logseq/Documents/Logseq_First_Database
index.1ca59d04.js:1 [Inbox Telegram] Started!
index.1ca59d04.js:1 [Inbox Telegram] Polling started!
index.1ca59d04.js:1 Processing
index.1ca59d04.js:1 {messages: Array(0)}messages: [][[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
index.1ca59d04.js:1 Processing
index.1ca59d04.js:1 {messages: Array(0)}messages: [][[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()

**Comment by shady2k** [comment]
It seems that no new messages in your bot chat.

**Comment by noadminonly** [comment]
Thats strange. I start the Bot  and  send several Test [messages....]()
![5D9EE085-222E-49C9-95A3-55E275D84AC5](https://user-images.githubusercontent.com/27069717/211202604-a671a47e-5882-49e6-b0cc-9ec8920bbedc.jpeg)

**Comment by andyw8** [comment]
I'm having the same problem. I see it polling but the messages array is always empty.

**Comment by shady2k** [comment]
Very strange. Try to open this link in your browser `https://api.telegram.org/bot${botToken}/getUpdates`, replace ${botToken} with you bot token. Can you see any messages?

**Comment by noadminonly** [comment]
After i set my bot token. 


 <html><head></head><body>

ok | false
-- | --
error_code | 404
description | "Not Found"

</body></html>

**Comment by andyw8** [comment]
@shady2k I think you put an extra `$` in that URL. Without it, I get:

```json
{"ok":true,"result":[]}
```

**Comment by andyw8** [comment]
But if I send a message, then reload, I do see it:

```
{"ok":true,"result":[{"update_id":4688632,
"message":{"message_id":34,"from":{"id":5915182488,"is_bot":false,"first_name":"Andy","last_name":"Waite","language_code":"en"},"chat":{"id":5915182488,"first_name":"Andy","last_name":"Waite","type":"private"},"date":1673217985,"text":"hello world"}}]}
```

(then when I refresh it shows an empty array again).

**Comment by byheaven** [comment]
I met the same problem. Sending messages directly to the bot is not working. Then I added the bot in a private channel and set as admin. Now it works perfectly. Hope it helps.

**Comment by noadminonly** [comment]
That sounds interesting. Can you explain/describe how you did that 

_added the bot in a private channel and set as admin._

 Thanks

**Comment by byheaven** [comment]
Just creat a channel and add your bot

**Comment by noadminonly** [comment]
Thanks for the tip, that works for me too, so that completes the process for me.
