### ISSUE TITLE
botTargetGraph Name Issue

### ISSUE THREAD

**Issue by dv0zn3r** [shady2k/logseq-inbox-telegram-plugin#34]
Is there any specific way to input a name for `botTargetGraph`? Messages have stopped syncing after I have switched from using an active graph. I have tried `Name`, `Folder/Name`, `graph/Name`. I have restarted the plugin and reloaded the app. Switching back to active graph successfully loads messages.

**Comment by shady2k** [comment]
Maybe you didn't wait for the polling period? Try restarting the plugin with the console open, and you will see the changes immediately.
