### ISSUE TITLE
[Inbox Telegram] Cannot get today's journal page

### ISSUE THREAD

**Issue by clickbrain** [shady2k/logseq-inbox-telegram-plugin#36]
I uninstalled and reinstalled and still getting this message.

My date format in Logseq is MM do, YYYY

**Comment by shady2k** [comment]
I need additional info, so do this:
- Open Logseq settings (three dots on top right corner) - Advanced - Developer mode and click on the toggle
- Go to your today journal page
- Three dots - (Dev) Show page data
- Click Copy to clipboard button and paste this text here

**Comment by clickbrain** [comment]
{:block/uuid #uuid "6536b8ae-ed7c-4c48-accd-e69b11014712",
 :block/journal? true,
 :block/updated-at 1698108882405,
 :block/created-at 1698085038861,
 :block/journal-day 20231023,
 :db/id 18452,
 :block/name "oct 23rd, 2023",
 :block/file {:db/id 18451}, 
 :block/original-name "Oct 23rd, 2023"}

**Comment by clickbrain** [comment]
Just sent multiple test messages and it is working. 

Literally has not worked for a few weeks until today. 

I did just do an update to LogSeq a few minutes ago, so maybe that is why it is working. 

Sorry to waste your time.
