### ISSUE TITLE
If i’am away from my computer...

### ISSUE THREAD

**Issue by bepolymathe** [shady2k/logseq-inbox-telegram-plugin#4]
Hi @shady2k 

Thanks for this great plugin ! I use it since its release and I'm very happy with it. I miss only one thing. 

When I'm away from my computer, I tend to want to write down a quick idea, a task in the robot's channel on telegram with the hope to find it afterwards. But it doesn't seem to work. Data is retrieved from telegram only when logseq and telegram are started together?

**Comment by shady2k** [comment]
No, you can write in Telegram anytime. When you open Logseq app with plugin it will pull all messages since last pulling.

**Comment by bepolymathe** [comment]
hum.... ok it works now. Sorry.

**Comment by shady2k** [comment]
I’m found bug in polling function in version 0.0.1. It was fixed in latest version. If you will encounter this problem in latest version, please, report about it.

**Comment by bepolymathe** [comment]
Actually I think I got it. I don't turn off the computer every time. I work a lot with a cellular connection and when I leave the work area with my phone the computer stays on and logseq open but there is no connection. When I return, the connection is restored but the telegram update is not. I have to reboot the application for it to work

**Comment by bepolymathe** [comment]
:+1: Thanks. Waiting for next update :wink: And thanks for this wonderful plugin !
