### ISSUE TITLE
invertMessagesOrder isn't working when inboxName is null

### ISSUE THREAD

**Issue by goldan** [shady2k/logseq-inbox-telegram-plugin#42]
Hi, thank you for such a useful plugin. 

Bug report: when inboxName is set to null, invertMessagesOrder setting is not respected: messages are added to the top of my daily page, not to the bottom. Restarting the plugin didn't help. Would it be possible to fix this?

**Comment by shady2k** [comment]
Can you check v1.0.5? Did it fix this issue?

**Comment by goldan** [comment]
Not really. Here is what I see in 0.1.5, after adding test and test2 messages:
<img width="153" alt="image" src="https://github.com/shady2k/logseq-inbox-telegram-plugin/assets/366892/26a8955b-d0c3-4705-bff8-c9ff785924b9">

**Comment by goldan** [comment]
I was able to fix it locally, please see my fork here: https://github.com/shady2k/logseq-inbox-telegram-plugin/compare/master...goldan:logseq-inbox-telegram-plugin:master
But I think the code needs to be refactored before merging.
