### ISSUE TITLE
How not to group entries

### ISSUE THREAD

**Issue by alxlg** [shady2k/logseq-inbox-telegram-plugin#5]
Your plugin is super useful, there is just a thing that bugs me: the fact that messages are childs of a block with a tag. I know I can set a different tag, but is there a way to disable this and just add new messages as parent blocks?

**Comment by shady2k** [comment]
Please, describe your use case. Why is this important to you?

**Comment by alxlg** [comment]
@shady2k thank you very much! I wanted it just to be consistent to my usual way to take notes
