### ISSUE TITLE
Cannot get today’s journal ?

### ISSUE THREAD

**Issue by bepolymathe** [shady2k/logseq-inbox-telegram-plugin#8]
Hi, 

![image](https://user-images.githubusercontent.com/29939805/151093854-f3dd68e2-1e6c-465e-a8d3-8bb1c29265eb.png)

What does this error message refer to? I simply deactivated/activated the plugin at the request of a developer of another plugin to do a test... and now I have this error message. :thinking:

**Comment by shady2k** [comment]
When trying to add messsages, plugin execute query:
```javascript
    ret = await logseq.DB.datascriptQuery(`
      [:find (pull ?p [*])
       :where
       [?b :block/page ?p]
       [?p :block/journal? true]
       [?p :block/journal-day ?d]
       [(= ?d ${todayDate})]]
    `);
```
Where `${todayDate}` - current date in format `YYYYMMDD`. In your case query return nothing.
Try to restart plugin and check you are on latest version.

**Comment by bepolymathe** [comment]
Hi @shady2k 

Thanks for reply. I have the 0.0.3 version. My config is like this and the problem persist

```
{
  "disabled": false,
  "botToken": "<My-TOKEN>",
  "inboxName": "📥 **INBOX** #Telegram",
  "pollingInterval": 60000,
  "inboxByChat": [],
}
```

My default date format is `dd-MM-yyyy` but i haven’t this problem before :thinking:

**Comment by bepolymathe** [comment]
I started from scratch by uninstalling and reinstalling the plugin calmly. It works. Thanks for your help. And thanks for this great plugin!

**Comment by clickbrain** [comment]
I uninstalled and reinstalled and still getting this message.
